# This yml will work after the images have been created and psuhed of the Basic implementation of the fullstack app
version: "3.9"

networks:
  bth-spark-net:
    driver: bridge

services:
  # auth service pushed image service
  server-auth:
    image: hihassan1998/spark-auth-server:1.0
    container_name: auth-api-server
    networks:
      - bth-spark-net
    ports:
      - "3001:3000"
    restart: unless-stopped
  
  # user service pushed image
  server-user:
    image: hihassan1998/spark-user-server:1.0
    container_name: user-api-server
    networks:
      - bth-spark-net
    ports:
      - "3002:3000"
    restart: unless-stopped
  
  # # frontend service pushed image user UI
  webclientuser:
    image: hihassan1998/spark-webclient-user:1.0
    container_name: spark-webclient-user
    networks:
      - bth-spark-net
    ports:
      - "3006:5173"
    restart: unless-stopped
  
  # frontend service pushed image admin UI
  webclientadmin:
    image: hihassan1998/spark-webclient-admin:1.0
    container_name: spark-webclient-admin
    networks:
      - bth-spark-net
    ports:
      - "3005:5173"
    restart: unless-stopped
    environment:
    - VITE_AUTH_API_URL=http://localhost:3000
    - VITE_SCOOTER_API_URL=http://localhost:3000/api/v1

  # frontend user mobile image
  # webclientusermob:
  #   # image: hihassan1998/spark-webclient-user-mobile:1.0
  #   container_name: spark-webclient-user-mobile
  #   networks:
  #     - bth-spark-net
  #   ports:
  #     - "3006:5173"
  #   restart: unless-stopped

